chore: bump sor to 4.10.1 - fix: ID_TO_NETWORK_NAME add unichain and monad testnet (#790)
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

- **What is the current behavior?** (You can also link to an open issue here)
routing-api release pipeline failed:

> Error: Unknown chain id: 41454
    at ID_TO_NETWORK_NAME (/codebuild/output/src1403594110/src/node_modules/@uniswap/smart-order-router/src/util/chains.ts:340:13)
    at /codebuild/output/src1403594110/src/bin/stacks/routing-dashboard-stack.ts:113:78
    at Array.map (<anonymous>)
    at /codebuild/output/src1403594110/src/bin/stacks/routing-dashboard-stack.ts:108:27
    at arrayMap (/codebuild/output/src1403594110/src/node_modules/lodash/lodash.js:653:23)
    at map (/codebuild/output/src1403594110/src/node_modules/lodash/lodash.js:9622:14)
    at Function.flatMap (/codebuild/output/src1403594110/src/node_modules/lodash/lodash.js:9325:26)
    at new RoutingDashboardStack (/codebuild/output/src1403594110/src/bin/stacks/routing-dashboard-stack.ts:102:57)
    at new RoutingAPIStack (/codebuild/output/src1403594110/src/bin/stacks/routing-api-stack.ts:245:5)
    at Object.<anonymous> (/codebuild/output/src1403594110/src/bin/app.ts:420:1)


- **What is the new behavior (if this is a feature change)?**
we should add unichain and monad testnet into ID_TO_NETWORK_NAME

- **Other information**: